apiVersion: v1
kind: Pod
metadata:
  name: ###
  labels:
    name: ###
spec:
  containers:
      - name: ###
        image: ###
        imagePullPolicy: Always
        ports:
        - containerPort: ###
        env:
          - name: ###
            value: "#"
